import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migrationPath = new URL(
  "../supabase/migrations/20260827000200_bibi_conversation_binding_onboarding.sql",
  import.meta.url,
);

async function migrationSql() {
  return readFile(migrationPath, "utf8");
}

test("legacy unproved verified binding is blocked, audited, and constrained by the migration", async () => {
  const db = new PGlite();
  await db.exec(`
    create table connector_nodes (id uuid primary key);
    create table conversations (
      id uuid primary key,
      owner_id uuid not null,
      sync_status text,
      sync_error text,
      updated_at timestamptz not null default now()
    );
    create table conversation_bindings (
      id uuid primary key,
      owner_id uuid not null,
      conversation_id uuid not null references conversations(id),
      binding_state text not null,
      initiation_source text not null default 'connector',
      verified_at timestamptz,
      verified_by_node_id uuid references connector_nodes(id),
      request_count integer not null default 1,
      verification_attempts integer not null default 0,
      organization_profile_id text,
      execution_profile_id text,
      hermes_session_id text,
      verification_code text,
      verification_error text,
      last_verification_at timestamptz,
      updated_at timestamptz not null default now()
    );
    create table conversation_audit_events (
      id bigint generated by default as identity primary key,
      owner_id uuid not null,
      conversation_id uuid not null,
      binding_id uuid,
      event_id text not null,
      event_type text not null,
      organization_profile_id text,
      execution_profile_id text,
      hermes_session_id text,
      payload jsonb not null default '{}'::jsonb,
      constraint conversation_audit_events_event_type_check
        check (event_type in ('pair', 'bind', 'project', 'unbind')),
      unique (owner_id, event_id)
    );

    insert into conversations (id, owner_id, sync_status)
    values ('00000000-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001', 'synced');
    insert into conversation_bindings (
      id, owner_id, conversation_id, binding_state,
      organization_profile_id, execution_profile_id, hermes_session_id
    ) values (
      '00000000-0000-0000-0000-000000000100',
      '00000000-0000-0000-0000-000000000001',
      '00000000-0000-0000-0000-000000000010',
      'verified', 'bibi-01', 'bibi-02', 'legacy-session'
    );
  `);

  const sql = await migrationSql();
  const start = sql.indexOf("-- A failed or revoked verification is a durable owner-visible fact.");
  const end = sql.indexOf("-- The idempotency key for \"create this binding\".");
  assert.ok(start >= 0 && end > start, "legacy remediation SQL block must be discoverable");
  await db.exec(sql.slice(start, end));

  const binding = await db.query(`
    select binding_state, verified_at, verified_by_node_id,
           verification_code, verification_attempts
      from conversation_bindings
     where id = '00000000-0000-0000-0000-000000000100'
  `);
  assert.deepEqual(binding.rows, [{
    binding_state: "blocked",
    verified_at: null,
    verified_by_node_id: null,
    verification_code: "LEGACY_UNPROVED_VERIFICATION",
    verification_attempts: 1,
  }]);

  const audit = await db.query(`
    select event_type, payload->>'code' as code
      from conversation_audit_events
     where binding_id = '00000000-0000-0000-0000-000000000100'
  `);
  assert.deepEqual(audit.rows, [{
    event_type: "verify_failed",
    code: "LEGACY_UNPROVED_VERIFICATION",
  }]);

  const conversation = await db.query(`
    select sync_status, sync_error from conversations
     where id = '00000000-0000-0000-0000-000000000010'
  `);
  assert.deepEqual(conversation.rows, [{
    sync_status: "blocked",
    sync_error: "LEGACY_UNPROVED_VERIFICATION",
  }]);

  const constraints = await db.query(`
    select conname, convalidated from pg_constraint
     where conname in (
       'conversation_bindings_verified_requires_connector_proof',
       'conversation_bindings_pending_is_unproven'
     ) order by conname
  `);
  assert.equal(constraints.rows.length, 2);
  assert.ok(constraints.rows.every((row) => row.convalidated === true));

  await assert.rejects(
    db.exec(`
      update conversation_bindings
         set binding_state = 'verified', verified_at = null, verified_by_node_id = null
       where id = '00000000-0000-0000-0000-000000000100'
    `),
    /conversation_bindings_verified_requires_connector_proof/i,
  );
  await db.close();
});

test("projection targets require durable connector proof in addition to verified state", async () => {
  const store = await readFile(new URL("../api/_lib/store.js", import.meta.url), "utf8");
  const targetQuery = store.slice(
    store.indexOf("async listProjectionTargets"),
    store.indexOf("async listPendingBindings"),
  );
  assert.match(targetQuery, /\.eq\("binding_state", "verified"\)/);
  assert.match(targetQuery, /\.not\("verified_at", "is", null\)/);
  assert.match(targetQuery, /\.not\("verified_by_node_id", "is", null\)/);
});

test("verified duplicate verification rechecks exact identity and recorded proof", async () => {
  const sql = await migrationSql();
  const verify = sql.slice(
    sql.indexOf("create or replace function public.bibi_verify_conversation_binding"),
    sql.indexOf("create or replace function public.bibi_fail_conversation_binding"),
  );
  const identityCheck = verify.indexOf("binding verification identity mismatch");
  const duplicateBranch = verify.indexOf("if v_binding.binding_state = 'verified' then");
  const proofCheck = verify.indexOf("verified binding is missing connector proof");
  assert.ok(identityCheck >= 0 && identityCheck < duplicateBranch);
  assert.ok(duplicateBranch >= 0 && proofCheck > duplicateBranch);
});
